### PR TITLE
[hotfix] -  url now is formatted according with UTF8

### PR DESCRIPTION
**Pull request by d4r1091**

### CODE REVIEW

**Comment by d4r1091** [comment]
What's exactly the error raised by TRAVIS?

**Comment by d4r1091** [comment]
up

**Comment by mukeshthawani** [comment]
Rebase it with the master.

**Comment by d4r1091** [comment]
should be alright now ;)

**Comment by mukeshthawani** [comment]
`stringByAddingPercentEscapesUsingEncoding` was depecated in iOS 9, it's better to replace `stringByAddingPercentEscapesUsingEncoding` with `stringByAddingPercentEncodingWithAllowedCharacters`

**Comment by d4r1091** [comment]
let me replace those then 👍

**Pull request closed without merging**
