### PR TITLE
FR: #402 - Move defines to header

### PR DESCRIPTION
**Pull request by adamsrosco**
for ALRegisterUserClientService #402

### CODE REVIEW

**Comment by adamsrosco** [comment]
Hi, Would this be able to go in as well.

Thanks.

**Comment by mukeshthawani** [comment]
Rebase it with the master

**Comment by adamsrosco** [comment]
Rebased. Travis busy running.

Thanks Mukesh.

**Comment by mukeshthawani** [comment]
Thanks Adam for the PR!

**Pull request merged**
